### ISSUE TITLE
Error de codificacion

### ISSUE THREAD

**Issue by Vosinepi** [abenassi/pyredatam#1]
Hay  un error de codificacion en el setup.py que crashea el pip

 [8 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\ismael\AppData\Local\Temp\pip-install-snw66c56\pyredatam_d51329fda0b14618b12c7547fe9b56cb\setup.py", line 15, in <module>
      readme = f.read()
    File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2052: character maps to <undefined>
  [end of output]

Saludos

**Comment by Vosinepi** [comment]
Agregando encoding='utf-8' a la linea 14 del setup parece solucionarse :

with open("README_PIP.rst", encoding='utf-8') as f:
    readme = f.read()
